# Generated by Django 4.2.21 on 2025-06-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
